name = "oortsnow/vide"
version = "0.4.6"
description = "A reactive Luau library for creating UI."
authors = ["oortsnow"]
repository = "https://github.com/oortsnow/vide"
license = "MIT"
includes = ["src/*", "README.md", "LICENSE.md", "pesde.toml"]

[target]
environment = "roblox"
build_files = ["src"]
lib = "src/init.luau"

[indices]
default = "https://github.com/pesde-pkg/index"
